<a href="https://colab.research.google.com/github/applemahmudd/Computer-Vision-Project/blob/main/Python_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=10

In [ ]:
name= "Apple Mahmud"
age= 27
weight= 65.5

In [ ]:
name=input("Enter your name")

Enter your nameApple Mahmud


In [ ]:
print(name)

Apple Mahmud


In [ ]:
print("Hello World")
print("Happy learning")

Hello World
Happy learning


In [ ]:
fruits=['apple','mango','banana']

In [ ]:
print(fruits[0])

apple


In [ ]:
print(fruits[2])

banana


In [ ]:
for i in fruits:
  print(i)

apple
mango
banana


In [ ]:
print(fruits[1])

mango


In [ ]:
age = 19
if age >= 18:
  print('Adult')

else:
  print('Child')



Adult


In [ ]:
def greet(name):
  print("hello",name)

  greet('Apple')


In [ ]:
print("Apple Mahmud \n 01609038230")

Apple Mahmud 
 01609038230


In [ ]:
print("Apple Mahmud \t 01774891467")

Apple Mahmud 	 01774891467


In [ ]:
print("\"Apple Mahmud\"")

"Apple Mahmud"


In [ ]:
name= "Shakib Al Hasan"
age= 25
print("My name is"+name)
print("I'm " , age , "years old")
print("I live in Dhaka")
print("I graduated from East West University")
print(name+" is my short name")
print( name+"Mahmud is my full name")

My name isShakib Al Hasan
I'm  25 years old
I live in Dhaka
I graduated from East West University
Shakib Al Hasan is my short name
Shakib Al HasanMahmud is my full name


In [ ]:
num1= 10
num2= 30
sum= num1+num2
print("Sum is" ,sum)

Sum is 40


In [ ]:
print(11+5)
print(11-5)
print(11*5)
print(11/5)
print(11%5)

16
6
55
2.2
1


In [ ]:
a= 50
b = 60

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

110
-10
3000
0.8333333333333334
50


In [ ]:
print(5 ** 3)

125


In [ ]:
name= input("Enter your name:")
age= input("Enter your age")
cgpa= input("Enter your cgpa")

print("Name is:",name)
print("Age is:",age)
print("Cgpa is:",cgpa)

Enter your name:Apple
Enter your age25
Enter your cgpa3.50
Name is: Apple
Age is: 25
Cgpa is: 3.50


numpy

In [ ]:
import numpy as np

In [ ]:
arr1= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
for row in arr1.flat:
  print(row)

1
2
3
4
5
6
7
8
9


Pandas

In [ ]:
import pandas as pd

In [ ]:
data= {
    "name": ["Rahim","Karim","Jamal","Apple"],
    "age": [25,30,28,27],
    "city": ["Dhaka", "Chittagong", "Sylet", "Rajshahi"]
}

In [ ]:
print(data)

{'name': ['Rahim', 'Karim', 'Jamal'], 'age': [25, 30, 28], 'city': ['Dhaka', 'Chittagong', 'Sylet']}


In [ ]:
pd.DataFrame(data)

name  age        city
0  Rahim   25       Dhaka
1  Karim   30  Chittagong
2  Jamal   28       Sylet
3  Apple   27    Rajshahi

In [ ]:
df=pd.read_csv("/Practise data Sheet1.csv")

XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)

Numpy for Linear Algebra in ML
np.linalg.det()
np.linalg.inv()
np.transpose()
np.dot()
np.cross() **bold text**

In [ ]:
import numpy as np

In [ ]:
A= np.array([[2, -1, 3],
             [4, 0, 5],
             [-2, 1, 4]])
B= np.array([[1, 3, -2],
             [4, -1, 0],
             [5, 2, 1]])

In [ ]:
print(A+B)

[[ 3  2  1]
 [ 8 -1  5]
 [ 3  3  5]]


In [ ]:
print(A-B)

[[ 1 -4  5]
 [ 0  1  5]
 [-7 -1  3]]


In [ ]:
print(np.dot(A,B))

[[13 13 -1]
 [29 22 -3]
 [22  1  8]]


In [ ]:
print(A@B)

[[13 13 -1]
 [29 22 -3]
 [22  1  8]]


In [ ]:
A= np.array([[2, -1, 3],
             [4, 0, 5],
             [-2, 1, 4]])
B= np.array([[1, 3, -2],
             [4, -1, 0],
             [5, 2, 1]])

Colmn wise


In [ ]:
cross_cols=[]

for i in range(3):
  a= A[:,i]
  b=B[:, i]

  print((np.cross(a,b)))
  #cross_cols.append(np.cross(a,b))

  #cross_cols = np.array(cross_cols)
  print(cross_cols)

[ 28 -12   4]
[]
[1 5 1]
[]
[  5 -11  10]
[]


Row wise

In [ ]:
cross_results = []

for i in range(3):
  a= A[i]
  b= B[i]
 #print((np.cross(a,b)))

  cross_results.append(np.cross(a,b))

cross_results = np.array(cross_results)
print(cross_results)


[[-7  7  7]
 [ 5 20 -4]
 [-7 22 -9]]


**Advance operation Inverse calculator**

In [ ]:
A= np.array([[1, 2, 3],
             [0, 1, 4],
             [5, 6, 0]])

In [ ]:
print(A)

[[1 2 3]
 [0 1 4]
 [5 6 0]]


**Determinant**

In [ ]:
det_A = np.linalg.det(A)
print(det_A)

0.9999999999999964


**Co-factor**

In [ ]:
def cofactor_matrix(M):
  C = np.zeros(M.shape)
  n= M.shape[0]

  for i in range(n):
    for j in range(n):
      minor = np.delete(np.delete(M, i, axis=0), j, axis=1)
      C[i, j] = ((-1)**(i+j)) * np.linalg.det(minor)
      return C



  C = cofactor_matrix(A)
  print(C)


In [ ]:
print(cofactor_matrix(A))

[[-24.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]]


In [ ]:
np.transpose(cofactor_matrix(A))

array([[-24.,   0.,   0.],
       [  0.,   0.,   0.],
       [  0.,   0.,   0.]])

In [ ]:
invA = np.linalg.inv(A)
print(invA)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [ ]:
!pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.12.0
access                                   1.1.9
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.2
aiosignal                                1.4.0
aiosqlite                                0.21.0
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.17.2
altair                                   5.5.0
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                                    4.12.0
anywidget                           

In [ ]:
%pwd

'/content'

In [ ]:
%ls

sample_data/


In [ ]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%bqsql  %%capture  %%debug  %%file  %%html  %%javascript  %%j

In [ ]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/Bt-BTidap0k?si=o3huZcUesbvbmbht" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
Arr1= np.array([2,3,4])

In [ ]:
print(Arr1)

[2 3 4]


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10, dtype= 'int32')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [ ]:
np.ones((4,2), dtype= 'int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [ ]:
np.full((5,6), 99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [ ]:
np.random.rand(4,2)

array([[0.4860164 , 0.61152036],
       [0.05358583, 0.08282274],
       [0.97326528, 0.79861306],
       [0.18072077, 0.02553532]])

In [ ]:
np.random.randint(1, 100, 20)

array([86, 84, 96, 34, 20, 29, 68, 44, 44,  2, 15, 82, 39, 27, 57, 61, 83,
       58, 75, 44])

In [ ]:
np.random.randint(-4,8, size=(3,3))

array([[-4, -2, -3],
       [ 7,  0, -1],
       [ 1,  3, -2]])

In [ ]:
np.random.randn(20)

array([ 0.27640723, -2.59973961,  0.90268832, -1.07494501, -0.9738991 ,
        0.56446667, -0.71981034, -0.63384788,  1.72823097,  0.89289993,
        1.43622083,  0.90058465, -1.23731426,  1.96050104,  0.07379683,
        0.44046482, -0.17668105,  1.31856062, -0.14872103, -1.38042091])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np

In [ ]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [ ]:
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

**Linspace**

In [ ]:
np.linspace(1,2,100, retstep=True)

(array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
        1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
        1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
        1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
        1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
        1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
        1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
        1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
        1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
        1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
        1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
        1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
        1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
        1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
        1.70707071, 1.71717172, 1.72727273, 1.73

In [ ]:
Mystep=np.linspace(9,15,20, retstep=True)
print(Mystep)

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
       10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
       12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
       13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]), np.float64(0.3157894736842105))


In [ ]:
np.linspace(1,30,50, retstep=True)

(array([ 1.        ,  1.59183673,  2.18367347,  2.7755102 ,  3.36734694,
         3.95918367,  4.55102041,  5.14285714,  5.73469388,  6.32653061,
         6.91836735,  7.51020408,  8.10204082,  8.69387755,  9.28571429,
         9.87755102, 10.46938776, 11.06122449, 11.65306122, 12.24489796,
        12.83673469, 13.42857143, 14.02040816, 14.6122449 , 15.20408163,
        15.79591837, 16.3877551 , 16.97959184, 17.57142857, 18.16326531,
        18.75510204, 19.34693878, 19.93877551, 20.53061224, 21.12244898,
        21.71428571, 22.30612245, 22.89795918, 23.48979592, 24.08163265,
        24.67346939, 25.26530612, 25.85714286, 26.44897959, 27.04081633,
        27.63265306, 28.2244898 , 28.81632653, 29.40816327, 30.        ]),
 np.float64(0.5918367346938775))

In [ ]:
array_2d=np.arange(24)
array_2d.shape = (6,4)
print(array_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
array_2d[2]

array([ 8,  9, 10, 11])

In [ ]:
array_2d[4]

array([16, 17, 18, 19])

In [ ]:
row= 5
colum= 2
array_2d[row, colum]

np.int64(22)

In [ ]:
array_2d[5][2]

np.int64(22)

In [ ]:
array_2d[:2, :2]

array([[0, 1],
       [4, 5]])

In [ ]:
array_2d[[0, 2, 3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
array_2d[:, [2]]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [ ]:
array_2d[[3, 0, 1]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

**1D Array**

In [ ]:
array_1d= np.array([-10, -2, 0, 2, 17, 106, 200])

In [ ]:
print(array_1d)

[-10  -2   0   2  17 106 200]


In [ ]:
array_1d[0]

np.int64(-10)

In [ ]:
array_1d[0:3]

array([-10,  -2,   0])

In [ ]:
array_1d[::]

array([-10,  -2,   0,   2,  17, 106, 200])

In [ ]:
array_1d[-2]

np.int64(106)

In [ ]:
array_1d[1:-2]

array([-2,  0,  2, 17])

In [ ]:
array_1d[:2], array_1d[2:]

(array([-10,  -2]), array([  0,   2,  17, 106, 200]))

In [ ]:
array_1d[0] = 102
print(array_1d)

[102  -2   0   2  17 106 200]


In [ ]:
import numpy as np

In [ ]:
array_ranint= np.random.randint(0,100,10)
print(array_ranint)

[80 20 90 63 64 76 13  6  4 49]


In [ ]:
array_ranint.min()

np.int64(4)

In [ ]:
array_ranint.max()

np.int64(90)

**koto number position e ei max number ase eta dai argmax()**

In [ ]:
array_ranint.argmax()

np.int64(2)

**koto number position e ei min number ase eta dai argmin()**

In [ ]:
array_ranint.argmin()

np.int64(8)

**Topic = size, shape, itemsize, nbytes, dtype, reshape**

In [ ]:
array_arange = np.arange(16)
print(array_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
array_arange.ndim

1

In [ ]:
array_arange.shape

(16,)

**itemsize mane 8 bytes kore jaiga dokhol koreche**

In [ ]:
array_arange.itemsize

8

In [ ]:
array_arange.size

16

**nbytes mane puro array amar 128 bytes jaiga dokhol koreche**

In [ ]:
array_arange.nbytes

128

In [ ]:
array_arange.dtype

dtype('int64')

**reshape er kaj holo 1D array ke 2D or dimension change kora**

In [ ]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
array_arange.shape = (4,4)
print(array_arange)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
import numpy as np

In [ ]:
array_arange.reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
array_arange.ndim

2

In [ ]:
array_arange.reshape(16,1).shape

(16, 1)

In [ ]:
array_arange.reshape(16,1).shape

(16, 1)

In [ ]:
array_arange.reshape(16,1).shape

(16, 1)

In [ ]:
array_arange.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
import numpy as np

In [ ]:
array_1D = np.arange(0,10)
print(array_1D)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
array_1D[0:5] = 500
print(array_1D)

[500 500 500 500 500   5   6   7   8   9]


In [ ]:
array_2D = np.ones((4,4))
print(array_2D)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
array_2D[0] = 300
print(array_2D)

[[300. 300. 300. 300.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]]


In [ ]:
array_2D + 300


array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])

In [ ]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print('Enter First Array')
print(a)
print('\n')

print('Enter Second Array')
print(b)
print('\n')

print('First Array + Second Array')
print(a+b)

Enter First Array
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Enter Second Array
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [ ]:
arr = np.arange(0,5)
print(arr)

[0 1 2 3 4]


In [ ]:
arr + arr

array([0, 2, 4, 6, 8])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16])

In [ ]:
arr / arr

/tmp/ipython-input-3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

/tmp/ipython-input-255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [ ]:
arr*2

array([0, 2, 4, 6, 8])

In [ ]:
2*arr

array([0, 2, 4, 6, 8])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
np.max(arr),  np.min(arr)

(np.int64(4), np.int64(0))

In [ ]:
arr.max()

np.int64(4)

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
array_2D = np.arange(30). reshape(6,5)
print(array_2D)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
array_2D.sum()

np.int64(435)

In [ ]:
array_2D.sum(axis=0)

array([75, 81, 87, 93, 99])

In [ ]:
array_2D.sum(axis=1)

array([ 10,  35,  60,  85, 110, 135])

In [ ]:
array_2D.std()

np.float64(8.65544144839919)

In [ ]:
import numpy as np

In [ ]:
filedata = np.genfromtxt('Practise data Sheet1.csv', delimiter=',')
filedata = filedata.astype('int64')
print(filedata)

[[-9223372036854775808 -9223372036854775808 -9223372036854775808
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808                    0                   40
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808                    0                   30
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808                    0 -9223372036854775808
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808                    0 -9223372036854775808
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808                    0 -9223372036854775808
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808                    0 -9223372036854775808
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808                    0 -9223372036854775808
  -9223372036854775808 -9223372036854775808]
 [-9223372036854775808                    5 -9223372036854775808
  -9223372036854775808 -9223372036854775808]
 [-9223372

/tmp/ipython-input-737831752.py:2: RuntimeWarning: invalid value encountered in cast
  filedata = filedata.astype('int64')


In [ ]:
filedata.shape

(61, 5)

In [ ]:
from numpy import loadtxt

In [ ]:
rawdata = open('Practise data Sheet1.csv', 'rb')
data = loadtxt(rawdata, delimiter=",")
print(data)


ValueError: could not convert string 'Keyword' to float64 at row 0, column 1.